project:
  type: website

website:
  title: "IIF Workshop on Open Source Forecasting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - program.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



