---
pagetitle: "Code of Conduct"
---

::::: grid
::: {#about_banner .g-col-12 .title}
# Code of Conduct
:::

::: {.g-col-12 .full_text_block}
## Code of Conduct

The organizers of this workshop are dedicated to providing a harassment-free conference experience for everyone regardless of age, gender, sexual orientation, disability, physical appearance, race, or religion (or lack thereof).

All participants (including attendees, speakers, sponsors and volunteers) are required to agree to the following code of conduct.

The code of conduct applies to all event activities including talks, discussions, and social events. It extends to conference-specific exchanges on social media.

Organizers will enforce this code throughout and expect cooperation in ensuring a safe environment for all.

## Expected Behaviour

All conference participants agree to:

-   Be considerate in language and actions, and respect the boundaries of fellow participants.
-   Refrain from demeaning, discriminatory, or harassing behaviour and language.
-   Alert a member of the code of conduct response team if you notice someone in distress, or observe violations of this code of conduct, even if they seem inconsequential.

## Unacceptable Behaviour

Behaviour that is unacceptable includes, but is not limited to:

-   Stalking
-   Deliberate intimidation
-   Unwanted photography or recording
-   Sustained or willful disruption of talks or other events
-   Use of sexual or discriminatory imagery, comments, or jokes
-   Offensive comments related to age, gender, sexual orientation, disability, race or religion
-   Inappropriate physical contact, which can include grabbing, or massaging or hugging without consent.
-   Unwelcome sexual attention, which can include inappropriate questions of a sexual nature, asking for sexual favours or repeatedly asking for dates or contact information.

If you are asked to stop harassing behaviour you should stop immediately, even if your behaviour was meant to be friendly or a joke, it was clearly not taken that way and for the comfort of all conference attendees you should stop.

Attendees who behave in a manner deemed inappropriate are subject to actions listed under Procedure for Code of Conduct Violations.

Presentation slides and posters should not contain offensive or sexualised material.

If this material is impossible to avoid given the topic (for example text mining of material from hate sites) the existence of this material should be noted in the abstract and, in the case of oral contributions, at the start of the talk or session.

## Procedure for Code of Conduct Violations

The organizing committee reserves the right to determine the appropriate response for all code of conduct violations.

Potential responses include:

-   a formal warning to stop harassing behaviour
-   expulsion from the event
-   removal of sponsor displays or event posters
-   cancellation or early termination of talks or other contributions to the program

## What To Do If You Witness or Are Subject To Unacceptable Behaviour

Alert the Code Of Conduct Response Team if you notice someone in distress, or observe violations of this code of conduct, even if they seem inconsequential.

Reports should be addressed to [mitch.ohara-wild@monash.edu](mailto:mitch.ohara-wild@monash.edu). If the report concerns someone from the response team, that member and everyone that would enter a conflict of interest will recuse themselves.

We will take all reports by participants seriously. This includes incidents outside our spaces and at any point in time. The organizing committee reserves the right to exclude people based on their past behavior, including behavior outside event spaces and behavior towards people who are not part of the event.

We will respect confidentiality requests for the purpose of protecting targets of harassing behavior. We will not name victims without their affirmative consent. Correspondence is handled confidentially and deleted after the case is resolved. All data is stored securely, access will be limited to the members of the Code Of Conduct Response Team who take the case.

Event organizers will also provide support to victims, including, but not limited to:

- Briefing key event staff to provide appropriate assistance.
- Other assistance to ensure victims feel safe for the duration of the conference.
- Assistance will only be provided with affirmative consent of the victim.

## Acknowledgements

This code of conduct was adapted from the [useR! conference's code of conduct](https://user2025.r-project.org/about/coc) and the [rOpenSci's code of conduct](https://ropensci.org/coc/).
:::
:::::
